# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180622_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 14, 58, 34, 239277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 22, 14, 58, 34, 238283, tzinfo=utc)),
        ),
    ]
